language: node_js

node_js:
  - '11.6.0'

matrix:
  include:
  - os: osx

cache:
  yarn: true

notifications:
  email: false

script:
  - yarn test
  - yarn dist

deploy:
  provider: releases
  api_key: $GH_TOKEN
  skip_cleanup: true
  on:
    tags: true

branches:
  only:
  - lane
