language: node_js

node_js: 

filter_secrets: false

env:
  matrix:
    secure: bin84NNLzfJp4hXkrGzA3iIHU9YJy1TGcwg5cw0pF6XZWBYgRS4evc9DMVKVWsu4ziIZPl/xH8yl0d/+US8/6OfjqI+8NtnJPJQL4Qc7J4NymrK3n0pRF56Nvm1k12o6yL05xo1VflOJhn6TE2ouLR1VN4mtPDZpxl8rkfLZKhv93bV+kCySIJO18SAOJ0D4i/wo64b31t+INAwvnsWP8J1DMeZO52BV7xb9J5ZgYA/JNcw08iPLjz4IEV8WwWG1SIg8sdvv3WfC6WVDdpguBCMYHsbjfJL7dcYkG0ThL6pCZeTJFcSAlHyY35S9tY+n1yEkrIM4tzm9Vi2iOyli+2gFpmX9NZjbwLKpUEjIQjkYoxMBJPvNsoPNqkY7XfyzBnKkFCUDCXQD466XmNuvOC3B3w1ck20dso3nXGlQDVPhEkDK7Wati35OmVLDaeg+m6ysazaQRUlJ7nJEXqbJi9vpma/RTNV+ea4SQjcX5ee+0Cwiv1cTwFJmLDBw1pCL128wMbrc3GMp6UPFIAYBj0iML2oBxy5fk6b+KD47khKz1x4duF2AtyNFLJyG3hI0I2J8ZVeBztrySZaTcv/pYAgILs64fYPPWkZjejTMaNty7FSYEIOXEY09/8lZ0XStp+H3Lajd25Dzep57fpJt+tl7JvLL4DFX+8KIrOFZOG8=

matrix:
  include:
  - os: osx
  - os: linux
    dist: ubuntu
    sudo: required
  - os: windows

cache:
  yarn: true

notifications:
  email: false

script:
- yarn test
- yarn dist

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  skip_cleanup: true
  on:
    branch: prod

branches:
  only:
  - master
