language: node_js

node_js:
  - '11.6.0'

matrix:
  allow_failures:
    - os: windows
  include:
    - os: osx
    - os: linux
      dist: ubuntu
      sudo: required
    - os: windows

cache:
  yarn: true

notifications:
  email: false

script:
- yarn test
- yarn dist

deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  skip_cleanup: true
  on:
    branch: prod

branches:
  only:
  - master
