language: node_js

node_js:
  - '11.6.0'

matrix:
  include:
    - os: osx
    - os: linux
      dist: ubuntu
      sudo: required
    ## - os: windows

cache:
  yarn: true

notifications:
  email: false

script:
  - yarn install --dev
  - yarn test

deploy:
  provider: script
  script: yarn dist
  on:
    branch: prod

branches:
  only:
  - prod
  - master
